# Generated by Django 4.2 on 2023-04-10 18:05

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_rename_employee_employeemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='job_description',
            field=tinymce.models.HTMLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=account.models.employee_image_rename),
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('contact_no', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpeg', upload_to=account.models.company_image_rename)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='account.companymodel'),
            preserve_default=False,
        ),
    ]
