# Generated by Django 4.2 on 2023-04-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_first_name_employeemodel_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
