# Generated by Django 4.2 on 2023-04-10 18:05

import asset_fort.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_fort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('asset_image', models.ImageField(default='default.jpeg', upload_to=asset_fort.models.asset_image_rename)),
                ('date_purchased', models.DateTimeField()),
                ('asset_issued', models.IntegerField(default=0)),
                ('asset_available', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset_fort.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
