# Generated by Django 4.2 on 2023-04-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_alter_companymodel_user'),
        ('asset_fort', '0003_assetmodel_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_asset', to='asset_fort.assetmodel')),
                ('asset_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignee', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_issued', to='account.employeemodel')),
            ],
        ),
    ]
