# Generated by Django 4.2 on 2023-04-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_fort', '0005_rename_assetissued_assetissuedmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetissuedmodel',
            old_name='employee',
            new_name='asset_assigned_to',
        ),
    ]
