# Generated by Django 4.2 on 2023-04-12 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_companymodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_fort', '0006_rename_employee_assetissuedmodel_asset_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetissuedmodel',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetissuedmodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='asset_condition_description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='asset_conditions',
            field=models.CharField(choices=[('VERY_GOOD', 'No maintenance required'), ('GOOD', 'Only normal maintenance required'), ('MINOR_DEFECT_ONLY', 'Minor maintenance required'), ('DEFECT', 'Minor maintenance required below(10%)'), ('MAINTENANCE_REQUIRED', 'Significant maintenance required (10-20%)'), ('REQUIRES_RENEWAL', 'Significant renewal/upgrade required (20-40%)'), ('ASSET_UNSERVICEABLE', 'Over(50%) of asset requires replacement')], default='VERY_GOOD', max_length=355),
        ),
        migrations.CreateModel(
            name='AssetLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(max_length=355)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('asset_conditions', models.CharField(choices=[('VERY_GOOD', 'No maintenance required'), ('GOOD', 'Only normal maintenance required'), ('MINOR_DEFECT_ONLY', 'Minor maintenance required'), ('DEFECT', 'Minor maintenance required below(10%)'), ('MAINTENANCE_REQUIRED', 'Significant maintenance required (10-20%)'), ('REQUIRES_RENEWAL', 'Significant renewal/upgrade required (20-40%)'), ('ASSET_UNSERVICEABLE', 'Over(50%) of asset requires replacement')], default='NONE', max_length=355)),
                ('asset_condition_description', tinymce.models.HTMLField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_asset_log', to='asset_fort.assetmodel')),
                ('asset_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_issued_log', to='account.employeemodel')),
                ('asset_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignee_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
