# Generated by Django 4.2 on 2023-04-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_fort', '0007_assetissuedmodel_is_returned_assetissuedmodel_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetlogmodel',
            old_name='asset_condition_description',
            new_name='return_asset_condition_description',
        ),
        migrations.RenameField(
            model_name='assetlogmodel',
            old_name='asset_conditions',
            new_name='return_asset_conditions',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='asset_available',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='asset_issued',
        ),
    ]
