# Generated by Django 4.2 on 2023-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_fort', '0010_rename_return_asset_conditions_assetissuedmodel_return_asset_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetissuedmodel',
            name='return_asset_condition',
        ),
        migrations.RemoveField(
            model_name='assetissuedmodel',
            name='return_asset_condition_description',
        ),
        migrations.AlterField(
            model_name='assetlogmodel',
            name='return_asset_conditions',
            field=models.CharField(choices=[('NONE', 'None'), ('VERY_GOOD', 'No maintenance required'), ('GOOD', 'Only normal maintenance required'), ('MINOR_DEFECT_ONLY', 'Minor maintenance required'), ('DEFECT', 'Minor maintenance required below(10%)'), ('MAINTENANCE_REQUIRED', 'Significant maintenance required (10-20%)'), ('REQUIRES_RENEWAL', 'Significant renewal/upgrade required (20-40%)'), ('ASSET_UNSERVICEABLE', 'Over(50%) of asset requires replacement')], default='NONE', max_length=355),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='asset_conditions',
            field=models.CharField(choices=[('NONE', 'None'), ('VERY_GOOD', 'No maintenance required'), ('GOOD', 'Only normal maintenance required'), ('MINOR_DEFECT_ONLY', 'Minor maintenance required'), ('DEFECT', 'Minor maintenance required below(10%)'), ('MAINTENANCE_REQUIRED', 'Significant maintenance required (10-20%)'), ('REQUIRES_RENEWAL', 'Significant renewal/upgrade required (20-40%)'), ('ASSET_UNSERVICEABLE', 'Over(50%) of asset requires replacement')], default='VERY_GOOD', max_length=355),
        ),
    ]
