# Generated by Django 4.2 on 2023-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_fort', '0012_assetissuedmodel_return_asset_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetissuedmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='assetissuedmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetissuedmodel',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AssetLogModel',
        ),
    ]
